version: "3"

networks:
  proxy-net:
    external: true

volumes:
  jellyfin-media:
    # # You can also mount a NFS volume from your other servers (e.g. NAS)
    # type: "nfs"
    # o: "addr=10.40.0.199,nolock,soft,rw"
    # device: ":/my/media"
  jellyfin-config:
  jellyfin-cache:

services:
  jellyfin:
    container_name: "jellyfin"
    image: "jellyfin/jellyfin:latest"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
    expose:
      - 8096
    networks:
      - proxy-net
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - jellyfin-media:/media
    environment:
      - JELLYFIN_PublishedServerUrl=https://media.home.easyselfhost.com
