version: '3'

networks:
  dns-net:
    ipam:
      driver: default
      config:
        - subnet: '172.16.238.0/24'

services:
  dnscrypt-proxy:
    image: 'easyselfhost/dnscrypt-proxy:latest'
    container_name: 'dnscrypt-proxy'
    restart: unless-stopped
    networks:
      dns-net:
        ipv4_address: '172.16.238.10'
    # volumes:
    #   - '${HOME}/docker-data/dns/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml'
  
  pihole:
    image: 'pihole/pihole:latest'
    container_name: 'pihole'
    restart: unless-stopped
    networks:
      - dns-net
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '8080:80/tcp'
    environment:
      WEBPASSWORD: 'your_password'
      PIHOLE_DNS_: '172.16.238.10'
    volumes:
      - '${HOME}/docker-data/dns/etc-pihole:/etc/pihole'
      - '${HOME}/docker-data/dns/etc-dnsmasq.d:/etc/dnsmasq.d'

    