version: '3'

networks:
  # create this network in command line using `docker network create proxy-net`
  proxy-net:
    name: proxy-net
    external: true

services:
  silverbullet:
    image: 'zefhemel/silverbullet:latest'
    container_name: 'silverbullet'
    restart: unless-stopped
    volumes: 
     - ${HOME}/docker-data/silverbullet:/space
    networks: 
     - default
     - proxy-net
  
  # Uncomment the following section if you don't have a Nginx Proxy Manager running
  # nginx:
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   container_name: 'nginx_proxy_manager'
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     # you can remove port 81 after you have HTTPS setup to your Nginx Proxy Manager admin page
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - '${HOME}/docker-data/nginx/data:/data'
  #     - '${HOME}/docker-data/nginx/letsencrypt:/etc/letsencrypt'
  #   networks:
  #     - default
  #     - proxy-net